#ifndef STYLEPROJECT_GLOBAL_H
#define STYLEPROJECT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STYLEPROJECT_LIBRARY)
#  define STYLEPROJECTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STYLEPROJECTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STYLEPROJECT_GLOBAL_H
